"""add user_id to nomad_metrics

Revision ID: 0f2d2d6a3c27
Revises: a3f8c1d92b45
Create Date: 2026-03-28 04:59:01.344461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2d2d6a3c27'
down_revision: Union[str, Sequence[str], None] = 'a3f8c1d92b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear test data since we're adding a NOT NULL column
    op.execute("DELETE FROM nomad_metrics")
    
    op.add_column('nomad_metrics', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'nomad_metrics', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_nomad_metrics_user_id'), 'nomad_metrics', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nomad_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_nomad_metrics_user_id'), table_name='nomad_metrics')
    op.drop_column('nomad_metrics', 'user_id')
    # ### end Alembic commands ###
