"""add group trip budget tracker

Revision ID: 7e18976465c2
Revises: 9f71b3e6aa10
Create Date: 2026-04-18 00:58:29.023067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e18976465c2'
down_revision: Union[str, Sequence[str], None] = '9f71b3e6aa10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_trip_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('alert_80_sent', sa.Boolean(), nullable=False),
    sa.Column('alert_100_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['group_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', name='uq_group_trip_budget_trip_id')
    )
    op.create_index(op.f('ix_group_trip_budgets_created_by_user_id'), 'group_trip_budgets', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_group_trip_budgets_trip_id'), 'group_trip_budgets', ['trip_id'], unique=False)
    op.create_table('group_trip_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('spent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['group_trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_trip_expenses_spent_at'), 'group_trip_expenses', ['spent_at'], unique=False)
    op.create_index(op.f('ix_group_trip_expenses_trip_id'), 'group_trip_expenses', ['trip_id'], unique=False)
    op.create_index(op.f('ix_group_trip_expenses_user_id'), 'group_trip_expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_trip_expenses_user_id'), table_name='group_trip_expenses')
    op.drop_index(op.f('ix_group_trip_expenses_trip_id'), table_name='group_trip_expenses')
    op.drop_index(op.f('ix_group_trip_expenses_spent_at'), table_name='group_trip_expenses')
    op.drop_table('group_trip_expenses')
    op.drop_index(op.f('ix_group_trip_budgets_trip_id'), table_name='group_trip_budgets')
    op.drop_index(op.f('ix_group_trip_budgets_created_by_user_id'), table_name='group_trip_budgets')
    op.drop_table('group_trip_budgets')
    # ### end Alembic commands ###
