"""add buddy matches table

Revision ID: add_buddy_matches_table
Revises: fcca6d262bb3
Create Date: 2026-04-17 00:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_buddy_matches_table'
down_revision: Union[str, Sequence[str], None] = 'fcca6d262bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('matched_user_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('common_interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('common_destinations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'matched_user_id', name='uq_buddy_match_pair')
    )
    op.create_index(op.f('ix_buddy_matches_matched_user_id'), 'buddy_matches', ['matched_user_id'], unique=False)
    op.create_index(op.f('ix_buddy_matches_user_id'), 'buddy_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buddy_matches_user_id'), table_name='buddy_matches')
    op.drop_index(op.f('ix_buddy_matches_matched_user_id'), table_name='buddy_matches')
    op.drop_table('buddy_matches')
    # ### end alembic commands ###
