"""add itinerary tables

Revision ID: afe87c85f3c1
Revises: 561d3d12166a
Create Date: 2026-03-28 04:30:19.827740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe87c85f3c1'
down_revision: Union[str, Sequence[str], None] = '561d3d12166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('travel_style', sa.String(length=20), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('itinerary_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('community_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['community_entry_id'], ['community_entries.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_activities_itinerary_id'), 'itinerary_activities', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_activities_itinerary_id'), table_name='itinerary_activities')
    op.drop_table('itinerary_activities')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
