"""add itinerary_id to group_trips

Revision ID: d370fa1a41a9
Revises: 7e18976465c2
Create Date: 2026-04-24 03:32:38.297133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370fa1a41a9'
down_revision: Union[str, Sequence[str], None] = '7e18976465c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_reviews_travel_style'), table_name='entry_reviews')
    op.add_column('group_trips', sa.Column('itinerary_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'group_trips', 'itineraries', ['itinerary_id'], ['id'])
    op.drop_index(op.f('ix_transit_fares_route_mode_submitted'), table_name='transit_fare_contributions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transit_fares_route_mode_submitted'), 'transit_fare_contributions', ['origin', 'destination', 'mode', 'submitted_at'], unique=False)
    op.drop_constraint(None, 'group_trips', type_='foreignkey')
    op.drop_column('group_trips', 'itinerary_id')
    op.create_index(op.f('ix_entry_reviews_travel_style'), 'entry_reviews', ['travel_style'], unique=False)
    # ### end Alembic commands ###
