/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips/index'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner/index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community/index'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated/trips/new'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips/$tripId'
import { Route as AuthenticatedCommunityNewRouteImport } from './routes/_authenticated/community/new'
import { Route as AuthenticatedCommunityEntryIdRouteImport } from './routes/_authenticated/community/$entryId'
import { Route as AuthenticatedPlannerItineraryIdIndexRouteImport } from './routes/_authenticated/planner/$itineraryId/index'
import { Route as AuthenticatedTripsJoinInviteCodeRouteImport } from './routes/_authenticated/trips/join/$inviteCode'
import { Route as AuthenticatedCommunityEntryIdEditRouteImport } from './routes/_authenticated/community/$entryId_.edit'
import { Route as AuthenticatedPlannerItineraryIdAccommodationsIndexRouteImport } from './routes/_authenticated/planner/$itineraryId/accommodations/index'
import { Route as AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRouteImport } from './routes/_authenticated/planner/$itineraryId/accommodations/$accommodationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityNewRoute =
  AuthenticatedCommunityNewRouteImport.update({
    id: '/community/new',
    path: '/community/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityEntryIdRoute =
  AuthenticatedCommunityEntryIdRouteImport.update({
    id: '/community/$entryId',
    path: '/community/$entryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlannerItineraryIdIndexRoute =
  AuthenticatedPlannerItineraryIdIndexRouteImport.update({
    id: '/planner/$itineraryId/',
    path: '/planner/$itineraryId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsJoinInviteCodeRoute =
  AuthenticatedTripsJoinInviteCodeRouteImport.update({
    id: '/trips/join/$inviteCode',
    path: '/trips/join/$inviteCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityEntryIdEditRoute =
  AuthenticatedCommunityEntryIdEditRouteImport.update({
    id: '/community/$entryId_/edit',
    path: '/community/$entryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlannerItineraryIdAccommodationsIndexRoute =
  AuthenticatedPlannerItineraryIdAccommodationsIndexRouteImport.update({
    id: '/planner/$itineraryId/accommodations/',
    path: '/planner/$itineraryId/accommodations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute =
  AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRouteImport.update(
    {
      id: '/planner/$itineraryId/accommodations/$accommodationId',
      path: '/planner/$itineraryId/accommodations/$accommodationId',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/community/$entryId/edit': typeof AuthenticatedCommunityEntryIdEditRoute
  '/trips/join/$inviteCode': typeof AuthenticatedTripsJoinInviteCodeRoute
  '/planner/$itineraryId/': typeof AuthenticatedPlannerItineraryIdIndexRoute
  '/planner/$itineraryId/accommodations/$accommodationId': typeof AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute
  '/planner/$itineraryId/accommodations/': typeof AuthenticatedPlannerItineraryIdAccommodationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/community/$entryId/edit': typeof AuthenticatedCommunityEntryIdEditRoute
  '/trips/join/$inviteCode': typeof AuthenticatedTripsJoinInviteCodeRoute
  '/planner/$itineraryId': typeof AuthenticatedPlannerItineraryIdIndexRoute
  '/planner/$itineraryId/accommodations/$accommodationId': typeof AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute
  '/planner/$itineraryId/accommodations': typeof AuthenticatedPlannerItineraryIdAccommodationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/_authenticated/community/new': typeof AuthenticatedCommunityNewRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/community/$entryId_/edit': typeof AuthenticatedCommunityEntryIdEditRoute
  '/_authenticated/trips/join/$inviteCode': typeof AuthenticatedTripsJoinInviteCodeRoute
  '/_authenticated/planner/$itineraryId/': typeof AuthenticatedPlannerItineraryIdIndexRoute
  '/_authenticated/planner/$itineraryId/accommodations/$accommodationId': typeof AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute
  '/_authenticated/planner/$itineraryId/accommodations/': typeof AuthenticatedPlannerItineraryIdAccommodationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/authenticated'
    | '/auth/callback'
    | '/community/$entryId'
    | '/community/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/community/'
    | '/planner/'
    | '/trips/'
    | '/community/$entryId/edit'
    | '/trips/join/$inviteCode'
    | '/planner/$itineraryId/'
    | '/planner/$itineraryId/accommodations/$accommodationId'
    | '/planner/$itineraryId/accommodations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/authenticated'
    | '/auth/callback'
    | '/community/$entryId'
    | '/community/new'
    | '/trips/$tripId'
    | '/trips/new'
    | '/community'
    | '/planner'
    | '/trips'
    | '/community/$entryId/edit'
    | '/trips/join/$inviteCode'
    | '/planner/$itineraryId'
    | '/planner/$itineraryId/accommodations/$accommodationId'
    | '/planner/$itineraryId/accommodations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/authenticated'
    | '/auth/callback'
    | '/_authenticated/community/$entryId'
    | '/_authenticated/community/new'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/new'
    | '/_authenticated/community/'
    | '/_authenticated/planner/'
    | '/_authenticated/trips/'
    | '/_authenticated/community/$entryId_/edit'
    | '/_authenticated/trips/join/$inviteCode'
    | '/_authenticated/planner/$itineraryId/'
    | '/_authenticated/planner/$itineraryId/accommodations/$accommodationId'
    | '/_authenticated/planner/$itineraryId/accommodations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/new': {
      id: '/_authenticated/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof AuthenticatedCommunityNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$entryId': {
      id: '/_authenticated/community/$entryId'
      path: '/community/$entryId'
      fullPath: '/community/$entryId'
      preLoaderRoute: typeof AuthenticatedCommunityEntryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/$itineraryId/': {
      id: '/_authenticated/planner/$itineraryId/'
      path: '/planner/$itineraryId'
      fullPath: '/planner/$itineraryId/'
      preLoaderRoute: typeof AuthenticatedPlannerItineraryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/join/$inviteCode': {
      id: '/_authenticated/trips/join/$inviteCode'
      path: '/trips/join/$inviteCode'
      fullPath: '/trips/join/$inviteCode'
      preLoaderRoute: typeof AuthenticatedTripsJoinInviteCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$entryId_/edit': {
      id: '/_authenticated/community/$entryId_/edit'
      path: '/community/$entryId/edit'
      fullPath: '/community/$entryId/edit'
      preLoaderRoute: typeof AuthenticatedCommunityEntryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/$itineraryId/accommodations/': {
      id: '/_authenticated/planner/$itineraryId/accommodations/'
      path: '/planner/$itineraryId/accommodations'
      fullPath: '/planner/$itineraryId/accommodations/'
      preLoaderRoute: typeof AuthenticatedPlannerItineraryIdAccommodationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/$itineraryId/accommodations/$accommodationId': {
      id: '/_authenticated/planner/$itineraryId/accommodations/$accommodationId'
      path: '/planner/$itineraryId/accommodations/$accommodationId'
      fullPath: '/planner/$itineraryId/accommodations/$accommodationId'
      preLoaderRoute: typeof AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedCommunityEntryIdRoute: typeof AuthenticatedCommunityEntryIdRoute
  AuthenticatedCommunityNewRoute: typeof AuthenticatedCommunityNewRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
  AuthenticatedCommunityEntryIdEditRoute: typeof AuthenticatedCommunityEntryIdEditRoute
  AuthenticatedTripsJoinInviteCodeRoute: typeof AuthenticatedTripsJoinInviteCodeRoute
  AuthenticatedPlannerItineraryIdIndexRoute: typeof AuthenticatedPlannerItineraryIdIndexRoute
  AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute: typeof AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute
  AuthenticatedPlannerItineraryIdAccommodationsIndexRoute: typeof AuthenticatedPlannerItineraryIdAccommodationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedCommunityEntryIdRoute: AuthenticatedCommunityEntryIdRoute,
  AuthenticatedCommunityNewRoute: AuthenticatedCommunityNewRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
  AuthenticatedCommunityEntryIdEditRoute:
    AuthenticatedCommunityEntryIdEditRoute,
  AuthenticatedTripsJoinInviteCodeRoute: AuthenticatedTripsJoinInviteCodeRoute,
  AuthenticatedPlannerItineraryIdIndexRoute:
    AuthenticatedPlannerItineraryIdIndexRoute,
  AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute:
    AuthenticatedPlannerItineraryIdAccommodationsAccommodationIdRoute,
  AuthenticatedPlannerItineraryIdAccommodationsIndexRoute:
    AuthenticatedPlannerItineraryIdAccommodationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
