/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community/index'
import { Route as AuthenticatedCommunityNewRouteImport } from './routes/_authenticated/community/new'
import { Route as AuthenticatedCommunityEntryIdRouteImport } from './routes/_authenticated/community/$entryId'
import { Route as AuthenticatedCommunityEntryIdEditRouteImport } from './routes/_authenticated/community/$entryId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityNewRoute =
  AuthenticatedCommunityNewRouteImport.update({
    id: '/community/new',
    path: '/community/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityEntryIdRoute =
  AuthenticatedCommunityEntryIdRouteImport.update({
    id: '/community/$entryId',
    path: '/community/$entryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityEntryIdEditRoute =
  AuthenticatedCommunityEntryIdEditRouteImport.update({
    id: '/community/$entryId_/edit',
    path: '/community/$entryId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/community/$entryId/edit': typeof AuthenticatedCommunityEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/community/$entryId/edit': typeof AuthenticatedCommunityEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/community/$entryId': typeof AuthenticatedCommunityEntryIdRoute
  '/_authenticated/community/new': typeof AuthenticatedCommunityNewRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/community/$entryId_/edit': typeof AuthenticatedCommunityEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/authenticated'
    | '/auth/callback'
    | '/community/$entryId'
    | '/community/new'
    | '/community/'
    | '/community/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/authenticated'
    | '/auth/callback'
    | '/community/$entryId'
    | '/community/new'
    | '/community'
    | '/community/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/authenticated'
    | '/auth/callback'
    | '/_authenticated/community/$entryId'
    | '/_authenticated/community/new'
    | '/_authenticated/community/'
    | '/_authenticated/community/$entryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/new': {
      id: '/_authenticated/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof AuthenticatedCommunityNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$entryId': {
      id: '/_authenticated/community/$entryId'
      path: '/community/$entryId'
      fullPath: '/community/$entryId'
      preLoaderRoute: typeof AuthenticatedCommunityEntryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$entryId_/edit': {
      id: '/_authenticated/community/$entryId_/edit'
      path: '/community/$entryId/edit'
      fullPath: '/community/$entryId/edit'
      preLoaderRoute: typeof AuthenticatedCommunityEntryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedCommunityEntryIdRoute: typeof AuthenticatedCommunityEntryIdRoute
  AuthenticatedCommunityNewRoute: typeof AuthenticatedCommunityNewRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedCommunityEntryIdEditRoute: typeof AuthenticatedCommunityEntryIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedCommunityEntryIdRoute: AuthenticatedCommunityEntryIdRoute,
  AuthenticatedCommunityNewRoute: AuthenticatedCommunityNewRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedCommunityEntryIdEditRoute:
    AuthenticatedCommunityEntryIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
